---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.windows
    version: ">=2.1.0"
  - name: chocolatey.chocolatey
    version: ">=1.5.0"
  - name: community.windows
    version: ">=2.0.0"

