---
# FRC Team 8626 - Windows Laptop Fleet Management Playbook
# This playbook configures Windows 11 laptops with FRC competition software
#
# Usage:
#   ansible-playbook site.yml                    # Run all roles
#   ansible-playbook site.yml --tags chrome      # Run only Chrome role
#   ansible-playbook site.yml --limit laptop-01  # Run on specific host
#
# Prerequisites:
#   1. Run scripts/setup_winrm.ps1 on each Windows laptop
#   2. Update inventory/hosts.yml with laptop IPs
#   3. Update group_vars/windows.yml with credentials

- name: Configure FRC Windows Laptops
  hosts: windows
  gather_facts: true

  pre_tasks:
    - name: Display target information
      ansible.builtin.debug:
        msg: "Configuring {{ inventory_hostname }} ({{ ansible_host }})"

    - name: Verify Windows version
      ansible.builtin.debug:
        msg: "Windows Version: {{ ansible_facts['os_name'] | default('Unknown') }} - {{ ansible_facts['os_version'] | default('Unknown') }}"

  roles:
    - role: common
      tags:
        - common
        - always

    - role: chrome
      tags:
        - chrome
        - browsers

    - role: ni_tools
      tags:
        - ni_tools
        - ni
        - frc_core

    - role: rev_client
      tags:
        - rev_client
        - rev
        - hardware

    - role: ctre_phoenix
      tags:
        - ctre_phoenix
        - ctre
        - phoenix
        - hardware

    - role: wpilib
      tags:
        - wpilib
        - frc_core
        - development

    - role: pathplanner
      tags:
        - pathplanner
        - autonomous

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          ========================================
          FRC software installation complete!
          
          Installed software:
          - Google Chrome
          - NI FRC Game Tools
          - REV Hardware Client
          - Phoenix Tuner X
          - WPILib VS Code
          - PathPlanner
          
          Desktop shortcuts have been created.
          A reboot may be required for some components.
          ========================================

    - name: Check if reboot is required
      ansible.windows.win_shell: |
        $rebootRequired = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired" -ErrorAction SilentlyContinue) -ne $null
        if ($rebootRequired) { "REBOOT_REQUIRED" } else { "NO_REBOOT" }
      register: reboot_check
      changed_when: false

    - name: Notify if reboot is required
      ansible.builtin.debug:
        msg: "*** REBOOT REQUIRED *** Please reboot this machine to complete installation."
      when: "'REBOOT_REQUIRED' in reboot_check.stdout"

